<?php

function localghost_menu() {
  $items['admin/config/localghost/configure'] = array(
    'title' => 'Local Ghost',
    'description' => 'Configure LocalGhost',
    'page callback' => 'localghost_configure',
    'access arguments' => array('configure localghost')
  );
  return $items;
}

function localghost_configure() {
	//Configuration for localghost
	return "Nothing here. Move along.";
}

function localghost_page_alter(&$page) {
	$page_array = $page;
	$path = request_path();
	if(empty($path)) $path = 'index';
	$html = drupal_render($page_array);
	$html_file = file_save_data($html, 'public://localghost/' . $path . '.html', FILE_EXISTS_REPLACE);
}